# Generated by Django 3.0.8 on 2020-08-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cutprice',
            field=models.IntegerField(default=0),
        ),
    ]
