# Generated by Django 3.0.8 on 2020-08-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_cutprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='save',
            field=models.IntegerField(default=0),
        ),
    ]
