# Generated by Django 3.0.8 on 2020-08-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='save',
            new_name='you_save',
        ),
    ]
