# Generated by Django 3.0.8 on 2020-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200810_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=500)),
                ('review', models.CharField(max_length=50000)),
            ],
        ),
    ]
