# Generated by Django 3.0.8 on 2020-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200812_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='revid',
            field=models.IntegerField(default=0),
        ),
    ]
