# Generated by Django 3.0.8 on 2020-08-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_review_revid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='revid',
            field=models.IntegerField(default=0),
        ),
    ]
