# Generated by Django 3.0.8 on 2020-08-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_review_revid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
    ]
