# Generated by Django 3.0.8 on 2020-08-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='No_of_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
