# Generated by Django 3.0.8 on 2020-08-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200827_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='No_of_images',
            new_name='Number_of_images',
        ),
    ]
