# Generated by Django 3.0.8 on 2020-09-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
