# Generated by Django 3.0.8 on 2020-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
