# Generated by Django 3.0.8 on 2020-09-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20200904_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pname1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pname2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pname3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pname4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pname5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pname6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity6',
        ),
        migrations.AddField(
            model_name='order',
            name='p_id1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_id2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_id3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_id4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_id5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_id6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_name1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_name2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_name3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_name4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_name5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_name6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_quantity1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_quantity2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_quantity3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_quantity4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_quantity5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='p_quantity6',
            field=models.CharField(default='', max_length=50),
        ),
    ]
