# Generated by Django 3.0.8 on 2020-09-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_review_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
